version: '3.7'

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

x-ember-defaults: &ember
  tty: true
  init: true
  image: danlynn/ember-cli:3.8.1
  entrypoint: ["bash"]
  working_dir: /myapp
  volumes:
    - .:/myapp:cached
    - ./node_modules:/myapp/node_modules:delegated
    - yarn-cache:/.yarn-cache
  environment:
    <<: *env

services:
  commands:
    <<: *ember
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]

  terminal:
    <<: *ember
    entrypoint: ["/bin/bash"]

  yarn:
    <<: *ember
    entrypoint: ["yarn"]

  ember:
    <<: *ember
    entrypoint: ["node_modules/.bin/ember"]

  manage:
    <<: *ember
    entrypoint: ["node_modules/.bin/ember"]
    command: ["serve", "--port", "8285", "--live-reload-port", "8286", "--proxy", "http://host.docker.internal:8288"]
    restart: on-failure
    ports:
      - "8285:8285"
      - "8286:8286"
      - "8287:8287"

volumes:
  yarn-cache: {}
